default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development: &development
  <<: *default
  database: iostux
  username: postgres
  password: iostux
  host: localhost
  port: 6432

test:
  <<: *development
  database: iostux_test

production:
  <<: *development
